---
- hosts: SERVERS
  become: true

  tasks:
  
    - name: Disable password authentication for SSH
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regex: "^PasswordAuthentication (yes|no)"
        line: "PasswordAuthentication no"

    - name: Enable public key authentication
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regex: "^PubkeyAuthentication (yes|no)"
        line: "PubkeyAuthentication yes"
      
    - name:  
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'ca-certificates', 'curl', 'gnupg', 'lsb-release']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name:  Set up the repository.
      shell: |
         echo
         "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu
         (lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt package index and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest